export const SEARCH_FOCUS = "header/search_focus"
export const SEARCH_BLUR = "header/search_blur"
export const SEARCH_LIST = "header/search_list"
export const CHANGE_PAGE = "header/change_page"
export const MOUSE_IN = "header/mouse_in"
export const MOUSE_OUT = "header/mouse_out"
export const TOGGLE_BACK_TOP = "header/TOGGLE_BACK_TOP"